<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Moonshine.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moonshine.Protocol\Moonshine.Protocol.csproj" />
    <ProjectReference Include="..\Moonshine.Interop\Moonshine.Interop.csproj" />
    <ProjectReference Include="..\Moonshine.Core\Moonshine.Core.csproj" />
    <ProjectReference Include="..\Moonshine.Host\Moonshine.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" />
  </ItemGroup>
</Project>
