<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22000.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moonshine.Core\Moonshine.Core.csproj" />
    <ProjectReference Include="..\Moonshine.Interop\Moonshine.Interop.csproj" />
    <ProjectReference Include="..\Moonshine.Protocol\Moonshine.Protocol.csproj" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" />
  </ItemGroup>

</Project>
